USE [QuanLi]
GO

/****** Object:  StoredProcedure [dbo].[KHACHHANG_LAYDS]    Script Date: 12/12/2016 11:53:40 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [dbo].[KHACHHANG_LAYDS]
 AS
SELECT * FROM KHACHHANG
GO

